# Setup
title:        Lucas Lu's Tech Blog
tagline:      啊！李文勇
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Kuan Lu
  url:        lucas95123@outlook.com

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
